apiVersion: 1

datasources:
  - name: InfluxDB
    uid: readtimeout-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    jsonData:
      httpMode: GET
      timeInterval: "5s"
    editable: true
